//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaFormaProject.Application.Validations.ResourcesMensagesError {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlunoMensagesError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlunoMensagesError() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NovaFormaProject.Application.Validations.ResourcesMensagesError.AlunoMensagesErro" +
                            "r", typeof(AlunoMensagesError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O aluno não existe..
        /// </summary>
        public static string ALUNO_NOT_FOUND {
            get {
                return ResourceManager.GetString("ALUNO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O contato do aluno deve ser um número de telefone válido. Aceita formatos como (99) 99999-9999 ou 99999-9999.
        /// </summary>
        public static string CONTATO_INVALIDO {
            get {
                return ResourceManager.GetString("CONTATO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O contato do aluno deve ser informado..
        /// </summary>
        public static string CONTATO_VAZIO {
            get {
                return ResourceManager.GetString("CONTATO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de inicio do aluno deve ser informada..
        /// </summary>
        public static string DATA_INICIO_ALUNO_VAZIO {
            get {
                return ResourceManager.GetString("DATA_INICIO_ALUNO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O endereço do aluno deve ser informado..
        /// </summary>
        public static string ENDERECO_VAZIO {
            get {
                return ResourceManager.GetString("ENDERECO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verifique se a data está no formato (dd/MM/yyyy).
        /// </summary>
        public static string FORMATO_DATA_INVALIDO {
            get {
                return ResourceManager.GetString("FORMATO_DATA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do aluno não pode exceder 100 caracteres..
        /// </summary>
        public static string MAXIMUM_LENGTH_ALUNO_NAME {
            get {
                return ResourceManager.GetString("MAXIMUM_LENGTH_ALUNO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O endereço do aluno não pode exceder 100 caracteres..
        /// </summary>
        public static string MAXIMUM_LENGTH_ENDERECO {
            get {
                return ResourceManager.GetString("MAXIMUM_LENGTH_ENDERECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do aluno deve conter no minimo 5 caracteres.
        /// </summary>
        public static string MINIMUM_LENGTH_ALUNO_NAME {
            get {
                return ResourceManager.GetString("MINIMUM_LENGTH_ALUNO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O endereço do aluno deve conter no minimo 15 caracteres.
        /// </summary>
        public static string MINIMUM_LENGTH_ENDERECO {
            get {
                return ResourceManager.GetString("MINIMUM_LENGTH_ENDERECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do aluno deve ser informado..
        /// </summary>
        public static string NOME_VAZIO {
            get {
                return ResourceManager.GetString("NOME_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status do aluno inválido..
        /// </summary>
        public static string STATUS_ALUNO_INVALIDO {
            get {
                return ResourceManager.GetString("STATUS_ALUNO_INVALIDO", resourceCulture);
            }
        }
    }
}
