//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaFormaProject.Application.Validations.ResourcesMensagesError {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PagamentoMensagesError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagamentoMensagesError() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NovaFormaProject.Application.Validations.ResourcesMensagesError.PagamentoMensages" +
                            "Error", typeof(PagamentoMensagesError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O aluno deve estar ativo para realisar um pagamento..
        /// </summary>
        internal static string ALUNO_INATIVO {
            get {
                return ResourceManager.GetString("ALUNO_INATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O aluno informado não existe..
        /// </summary>
        internal static string ALUNO_INVALIDO {
            get {
                return ResourceManager.GetString("ALUNO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O aluno é obrigatório..
        /// </summary>
        internal static string ALUNO_VAZIO {
            get {
                return ResourceManager.GetString("ALUNO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de pagamento não pode ser no futuro..
        /// </summary>
        internal static string DATA_PAGAMENTO_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_PAGAMENTO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de vencimento do pagamento deve ser no futuro..
        /// </summary>
        internal static string DATA_VENCIMENTO_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_VENCIMENTO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de vencimento do pagamento é obrigatória..
        /// </summary>
        internal static string DATA_VENCIMENTO_VAZIO {
            get {
                return ResourceManager.GetString("DATA_VENCIMENTO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verifique se a data está no formato (dd/MM/yyyy)..
        /// </summary>
        internal static string FORMATO_DATA_INVALIDO {
            get {
                return ResourceManager.GetString("FORMATO_DATA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O pagamento informado não existe..
        /// </summary>
        internal static string PAGAMENTO_NOT_FOUND {
            get {
                return ResourceManager.GetString("PAGAMENTO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status do pagamento inválido..
        /// </summary>
        internal static string STATUS_PAGAMENTO_INVALIDO {
            get {
                return ResourceManager.GetString("STATUS_PAGAMENTO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O status do pagamento é obrigatório..
        /// </summary>
        internal static string STATUS_PAGAMENTO_VAZIO {
            get {
                return ResourceManager.GetString("STATUS_PAGAMENTO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor do pagamento deve ser maior ou igual a zero.
        /// </summary>
        internal static string VALOR_INVALIDO {
            get {
                return ResourceManager.GetString("VALOR_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor do pagamento é obrigatório..
        /// </summary>
        internal static string VALOR_VAZIO {
            get {
                return ResourceManager.GetString("VALOR_VAZIO", resourceCulture);
            }
        }
    }
}
